-- Datos extraidos de MEMORIA_COMPETICION_INTERNA_1998-99.pdf
-- Liga separada de Colegios Mayores excluida; Colegios Mayores incluidos cuando aparecen en Trofeo Alfonso XIII.
-- En las fases finales del Trofeo Rector, el puesto corresponde a la fase final; los puntos corresponden a la liga/clasificacion previa.
-- Revisado a fondo (2026-08-16) contra el PDF: secciones 2.x (1a categoria), 3.x (2a categoria + Ligas de Ascenso),
-- 4.x (Trofeo Alfonso XIII, clasificacion final real), y 10.x (Ascensos y Descensos, fuente autoritativa de asc_desc).
-- Puestos/puntos/asc_desc/alfonso de facultades ya eran correctos en el borrador original; unica correccion aplicada:
-- las 9 filas de CMU que solo aparecen en el Trofeo Alfonso XIII tenian puesto/puntos del mini-torneo interno del
-- trofeo (partidos entre CMUs), corregidos a NULL/NULL segun la convencion del proyecto (alfonso conserva su posicion).
START TRANSACTION;
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'ECONOMICAS', 'm', 1, 20, 1, 0, 1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'ESCUNI', 'm', 2, 16, 1, 0, 2);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'DERECHO', 'm', 3, 16, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'MATEMATICAS', 'm', 4, 12, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'E.S.I.C.', 'm', 5, 10, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'POLITICAS', 'm', 6, 8, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'GEOGRAFIA E HISTORIA', 'm', 7, 6, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'MEDICINA', 'm', 8, 6, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'GEOLOGICAS', 'm', 9, 4, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'FISICAS', 'm', 10, 4, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'QUIMICAS', 'm', 11, 2, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'EDUCACION', 'm', -1, NULL, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'ESCUNI', 'f', 1, 18, 1, 0, 1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'POLITICAS', 'f', 2, 18, 1, 0, 2);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'MATEMATICAS', 'f', 3, 14, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'DERECHO', 'f', 4, 14, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'GEOLOGICAS', 'f', 5, 12, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'ECONOMICAS', 'f', 6, 10, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'GEOGRAFIA E HISTORIA', 'f', 7, 8, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'FARMACIA', 'f', 8, 6, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'VETERINARIA', 'f', 9, 6, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'FISICAS', 'f', 10, 2, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'EMPRESARIALES', 'f', 11, -2, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'EDUCACION', 'f', -1, NULL, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONMANO', 'ECONOMICAS', 'm', 1, 12, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONMANO', 'MATEMATICAS', 'm', 2, 10, 1, 0, 1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONMANO', 'GEOLOGICAS', 'm', 3, 8, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONMANO', 'FARMACIA', 'm', 4, 6, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONMANO', 'GEOGRAFIA E HISTORIA', 'm', 5, 4, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONMANO', 'FISICAS', 'm', 6, 1, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONMANO', 'QUIMICAS', 'm', 7, -1, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONMANO', 'C. INFORMACION', 'm', -1, NULL, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONMANO', 'POLITICAS', 'm', -1, NULL, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'DERECHO', 'm', 1, 18, 1, 0, 1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'GEOLOGICAS', 'm', 2, 15, 1, 0, 2);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'ECONOMICAS', 'm', 3, 15, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'MATEMATICAS', 'm', 4, 13, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'MEDICINA', 'm', 5, 13, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'QUIMICAS', 'm', 6, 12, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'C. JURIDICAS', 'm', 7, 11, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'FISICAS', 'm', 8, 9, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'RAMON CARANDE', 'm', 9, 9, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'C. INFORMACION', 'm', 10, 7, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'FILOLOGIA', 'm', 11, 6, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'EMPRESARIALES', 'm', 12, 4, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'C. INFORMACION', 'f', 1, 19, 1, 0, 2);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'DERECHO', 'f', 2, 19, 1, 0, 1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'MATEMATICAS', 'f', 3, 16, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'POLITICAS', 'f', 4, 14, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'QUIMICAS', 'f', 5, 14, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'RAMON CARANDE', 'f', 6, 13, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'FARMACIA', 'f', 7, 12, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'GEOLOGICAS', 'f', 8, 10, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'ODONTOLOGIA', 'f', 9, 7, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'EDUCACION', 'f', 10, 6, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'ECONOMICAS', 'f', 11, 2, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'FISICAS', 'f', 12, 0, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'E.S.I.C.', 'm', 1, 21, 1, 0, 4);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'VETERINARIA', 'm', 2, 20, 1, 0, 3);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'CARDENAL CISNEROS', 'm', 3, 19, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'C. INFORMACION', 'm', 4, 19, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'C. JURIDICAS', 'm', 5, 13, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'MATEMATICAS', 'm', 6, 13, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'GEOGRAFIA E HISTORIA', 'm', 7, 10, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'DERECHO', 'm', 8, 9, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'MEDICINA', 'm', 9, 8, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'C.U.N.E.F.', 'm', 10, 7, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'ESTADISTICA', 'm', 11, 6, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'FARMACIA', 'm', 12, 5, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'RAMON CARANDE', 'm', 13, 4, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'ECONOMICAS', 'm', -1, NULL, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'FARMACIA', 'm', 1, 20, 1, 0, 2);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'FISICAS', 'm', 2, 16, 1, 0, 3);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'DERECHO', 'm', 3, 16, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'VETERINARIA', 'm', 4, 10, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'MATEMATICAS', 'm', 5, 10, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'E.S.I.C.', 'm', 6, 8, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'QUIMICAS', 'm', 7, 8, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'CARDENAL CISNEROS', 'm', 8, 7, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'POLITICAS', 'm', 9, 7, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'EDUCACION', 'm', 10, 5, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'GEOLOGICAS', 'm', 11, 3, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'PSICOLOGIA', 'm', -1, NULL, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'POLITICAS', 'f', 1, 14, 1, 0, 1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'FISICAS', 'f', 2, 12, 1, 0, 2);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'MATEMATICAS', 'f', 3, 8, 1, 0, 3);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'GEOLOGICAS', 'f', 4, 6, 1, 0, 4);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'GEOGRAFIA E HISTORIA', 'f', 5, 0, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'EDUCACION', 'f', -1, NULL, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'FARMACIA', 'm', 1, 18, 1, 0, 1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'ECONOMICAS', 'm', 2, 16, 1, 0, 3);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'GEOLOGICAS', 'm', 3, 14, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'DERECHO', 'm', 4, 10, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'FISICAS', 'm', 5, 10, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'E.S.I.C.', 'm', 6, 6, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'PSICOLOGIA', 'm', 7, 6, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'POLITICAS', 'm', 8, 4, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'MATEMATICAS', 'm', 9, 2, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'INFORMATICA', 'm', 10, -2, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'QUIMICAS', 'm', -1, NULL, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'C. FRANCISCO DE VITORIA', 'm', -1, NULL, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'FILOLOGIA', 'f', 1, 18, 1, 0, 2);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'FARMACIA', 'f', 2, 14, 1, 0, 3);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'PSICOLOGIA', 'f', 3, 14, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'MEDICINA', 'f', 4, 12, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'QUIMICAS', 'f', 5, 12, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'GEOLOGICAS', 'f', 6, 12, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'GEOGRAFIA E HISTORIA', 'f', 7, 10, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'C. INFORMACION', 'f', 8, 6, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'MATEMATICAS', 'f', 9, 6, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'ESCUNI', 'f', 10, 2, 1, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'POLITICAS', 'f', 11, 0, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'ECONOMICAS', 'f', -1, NULL, 1, -1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'FISICAS', 'm', 1, 16, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'GEOLOGICAS', 'm', 2, 12, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'BELLAS ARTES', 'm', 3, 12, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'ING. QUIMICA', 'm', 4, 10, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'FARMACIA', 'm', 5, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'GEOGRAFIA E HISTORIA', 'm', 6, 6, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'MEDICINA', 'm', 7, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'MATEMATICAS', 'm', 8, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'DERECHO', 'm', 9, -2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'C.U.N.E.F.', 'm', 1, 12, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'FOMENTO C.E.', 'm', 2, 8, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'RAMON CARANDE', 'm', 3, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'ESTADISTICA', 'm', 4, 6, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'BIOLOGIA II', 'm', 5, 6, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'POLITICAS', 'm', 6, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'C. INFORMACION', 'm', 7, 0, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'FILOSOFIA Y LETRAS', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'FILOLOGIA', 'm', 1, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'QUIMICAS', 'm', 2, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'INFORMATICA', 'm', 3, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'CARDENAL CISNEROS', 'm', 4, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'PSICOLOGIA', 'm', 5, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'OPTICA Y OPTOMETRIA', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'E.S.I.C.', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'EMPRESARIALES', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'C. JURIDICAS', 'm', 1, 14, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'ECONOMICAS', 'm', 2, 12, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'VETERINARIA', 'm', 3, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'TRABAJO SOCIAL', 'm', 4, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'C. FRANCISCO DE VITORIA', 'm', 5, 6, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'BIOLOGICAS', 'm', 6, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'DOCUMENTACION', 'm', 7, 0, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'ODONTOLOGIA', 'm', 8, 0, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'GEOLOGICAS', 'f', 1, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'BIOLOGICAS', 'f', 2, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'ING. QUIMICA', 'f', 3, 6, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'MEDICINA', 'f', 4, 6, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'GEOGRAFIA E HISTORIA', 'f', 5, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'FISICAS', 'f', 6, -2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'FILOSOFIA Y LETRAS', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'PSICOLOGIA', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'E.S.I.C.', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'CARDENAL CISNEROS', 'f', 1, 8, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'RAMON CARANDE', 'f', 2, 8, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'ESTADISTICA', 'f', 3, 6, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'C. INFORMACION', 'f', 4, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'C. FRANCISCO DE VITORIA', 'f', 5, 0, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'BELLAS ARTES', 'f', 6, 0, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'EMPRESARIALES', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONCESTO', 'TRABAJO SOCIAL', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'PSICOLOGIA', 'm', 1, 13, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'C. FRANCISCO DE VITORIA', 'm', 2, 11, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'GEOGRAFIA E HISTORIA', 'm', 3, 9, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'ODONTOLOGIA', 'm', 4, 9, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'ECONOMICAS', 'm', 5, 7, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'EMPRESARIALES', 'm', 6, 6, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'BELLAS ARTES', 'm', 7, 6, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'C. JURIDICAS', 'm', 8, 5, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'ING. QUIMICA', 'm', 9, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'VETERINARIA', 'm', 1, 12, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'INFORMATICA', 'm', 2, 11, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'FARMACIA', 'm', 3, 9, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'FILOLOGIA', 'm', 4, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'FISICAS', 'm', 5, 7, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'E.S.I.C.', 'm', 6, 5, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'OPTICA Y OPTOMETRIA', 'm', 7, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'PERSONAL', 'm', 8, -2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'VILLANUEVA', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'C.U.N.E.F.', 'm', 1, 9, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'BIOLOGICAS', 'm', 2, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'FILOSOFIA Y LETRAS', 'm', 3, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'POLITICAS', 'm', 4, 6, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'EDUCACION', 'm', 5, 5, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'TRABAJO SOCIAL', 'm', 6, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'DERECHO', 'm', 7, 0, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'C. INFORMACION', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'MEDICINA', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'ESCUNI', 'm', 1, 11, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'ESTADISTICA', 'm', 2, 9, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'MATEMATICAS', 'm', 3, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'BIOLOGIA II', 'm', 4, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'CARDENAL CISNEROS', 'm', 5, 7, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'QUIMICAS', 'm', 6, 6, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'RAMON CARANDE', 'm', 7, 3, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'GEOLOGICAS', 'm', 8, 0, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'DOCUMENTACION', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'GEOGRAFIA E HISTORIA', 'f', 1, 12, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'E.S.I.C.', 'f', 2, 9, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'VETERINARIA', 'f', 3, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'BIOLOGICAS', 'f', 4, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'MEDICINA', 'f', 5, 3, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'BELLAS ARTES', 'f', 6, 3, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'EMPRESARIALES', 'f', 7, 1, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'MATEMATICAS', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'PSICOLOGIA', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'C. INFORMACION', 'f', 1, 10, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'TRABAJO SOCIAL', 'f', 2, 8, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'BIOLOGIA II', 'f', 3, 5, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'C. JURIDICAS', 'f', 4, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'FILOLOGIA', 'f', 5, 3, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'CARDENAL CISNEROS', 'f', 6, 0, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'QUIMICAS', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'VILLANUEVA', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'PERSONAL', 'm', 1, 12, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'GEOLOGICAS', 'm', 2, 10, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'FILOLOGIA', 'm', 3, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'MATEMATICAS', 'm', 4, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'DERECHO', 'm', 5, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'RAMON CARANDE', 'm', 6, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'BELLAS ARTES', 'm', 7, -2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'FARMACIA', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'VETERINARIA', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'ECONOMICAS', 'm', 1, 14, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'PSICOLOGIA', 'm', 2, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'FISICAS', 'm', 3, 7, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'MEDICINA', 'm', 4, 7, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'TRABAJO SOCIAL', 'm', 5, 6, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'QUIMICAS', 'm', 6, 6, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'FOMENTO C.E.', 'm', 7, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'EMPRESARIALES', 'm', 8, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'POLITICAS', 'm', 1, 11, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'BIOLOGICAS', 'm', 2, 9, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'C. JURIDICAS', 'm', 3, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'OPTICA Y OPTOMETRIA', 'm', 4, 5, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'ODONTOLOGIA', 'm', 5, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'C. INFORMACION', 'm', 6, 3, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'E.S.I.C.', 'm', 7, 0, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'VILLANUEVA', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'CARDENAL CISNEROS', 'm', 1, 13, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'INFORMATICA', 'm', 2, 12, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'FILOSOFIA Y LETRAS', 'm', 3, 9, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'EDUCACION', 'm', 4, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'BIOLOGIA II', 'm', 5, 5, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'C. FRANCISCO DE VITORIA', 'm', 6, 5, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'GEOGRAFIA E HISTORIA', 'm', 7, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'ING. QUIMICA', 'm', 8, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'DERECHO', 'm', 1, 10, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'ECONOMICAS', 'm', 2, 6, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'EDUCACION', 'm', 3, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'RAMON CARANDE', 'm', 4, 0, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'CARDENAL CISNEROS', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'MEDICINA', 'm', 1, 12, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'GEOGRAFIA E HISTORIA', 'm', 2, 8, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'TRABAJO SOCIAL', 'm', 3, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'FOMENTO C.E.', 'm', 4, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'OPTICA Y OPTOMETRIA', 'm', 5, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'GEOLOGICAS', 'm', 6, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'RAMON CARANDE', 'm', 7, 0, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'C. INFORMACION', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'VETERINARIA', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'ESTADISTICA', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'FISICAS', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'EMPRESARIALES', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'BELLAS ARTES', 'm', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'FISICAS', 'f', 1, 8, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'ODONTOLOGIA', 'f', 2, 6, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'FOMENTO C.E.', 'f', 3, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'E.S.I.C.', 'f', 4, 4, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'FARMACIA', 'f', 5, 0, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'OPTICA Y OPTOMETRIA', 'f', 6, 0, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'EMPRESARIALES', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'PSICOLOGIA', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'RAMON CARANDE', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'GEOLOGICAS', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'GEOGRAFIA E HISTORIA', 'f', 1, 10, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'DOCUMENTACION', 'f', 2, 8, 2, 1, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'TRABAJO SOCIAL', 'f', 3, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'VETERINARIA', 'f', 4, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'DERECHO', 'f', 5, 2, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'BELLAS ARTES', 'f', 6, 0, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'BIOLOGICAS', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'C. FRANCISCO DE VITORIA', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'CARDENAL CISNEROS', 'f', -1, NULL, 2, 0, -1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'BALONMANO', 'C.M. MARQUES DE LA ENSENADA', 'm', NULL, NULL, 1, 0, 2);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'STA.M.ESTUDIAN.', 'f', NULL, NULL, 1, 0, 3);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL SALA', 'C.M. MIGUEL ANTONIO CARO', 'f', NULL, NULL, 1, 0, 4);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'C.M. SAN PABLO', 'm', NULL, NULL, 1, 0, 1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'FUTBOL 11', 'C.M. SAN AGUSTIN', 'm', NULL, NULL, 1, 0, 2);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'CISNEROS', 'm', NULL, NULL, 1, 0, 1);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'RUGBY', 'C.M. CHAMINADE', 'm', NULL, NULL, 1, 0, 4);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'C.M. PIO XII', 'm', NULL, NULL, 1, 0, 2);
INSERT INTO Clasificaciones (anio, deporte, equipo, genero, puesto, puntos, categoria, asc_desc, alfonso) VALUES ('1998-99', 'VOLEIBOL', 'C.M. SANTA MONICA', 'f', NULL, NULL, 1, 0, 1);
COMMIT;
